"""Study content loaded from content.json (generated by scripts/extract_content.py).

Holds all 143 topics of the course with their flashcards, Latin term pairs and test questions —
the same material the website serves, keyed by the same "<moduleId>:<topicNum>" scheme, so a
session run in the bot lands on the student's real progress.

Loaded once at import into module-level dicts; everything here is read-only lookup/sampling.
"""

from __future__ import annotations

import json
import random
import re
from pathlib import Path
from typing import Any, Optional

CONTENT_PATH = Path(__file__).with_name("content.json")

# module id -> list of topics: {num, name, lat?, cards[], pairs[], tests[]}
MODULES_CONTENT: dict[str, list[dict[str, Any]]] = {}
# "<moduleId>:<num>" -> topic
TOPIC_BY_KEY: dict[str, dict[str, Any]] = {}


def _load() -> None:
    if not CONTENT_PATH.exists():
        return
    with CONTENT_PATH.open(encoding="utf-8") as fh:
        data = json.load(fh)
    MODULES_CONTENT.update(data)
    for module_id, topics in data.items():
        for topic in topics:
            TOPIC_BY_KEY[f"{module_id}:{topic['num']}"] = topic


_load()


def topics_of(module_id: str) -> list[dict[str, Any]]:
    return MODULES_CONTENT.get(module_id, [])


def get_topic(module_id: str, topic_num: int) -> Optional[dict[str, Any]]:
    return TOPIC_BY_KEY.get(f"{module_id}:{topic_num}")


def topic_name(module_id: str, topic_num: int) -> str:
    topic = get_topic(module_id, topic_num)
    return topic.get("name", "") if topic else ""


def has_content() -> bool:
    return bool(MODULES_CONTENT)


def counts() -> dict[str, int]:
    topics = cards = pairs = tests = 0
    for module_topics in MODULES_CONTENT.values():
        topics += len(module_topics)
        for topic in module_topics:
            cards += len(topic.get("cards", []))
            pairs += len(topic.get("pairs", []))
            tests += len(topic.get("tests", []))
    return {"topics": topics, "cards": cards, "pairs": pairs, "tests": tests}


def _normalize(text: str) -> str:
    return re.sub(r"\s+", " ", (text or "").lower().strip())


def search_topics(query: str, limit: int = 12) -> list[dict[str, Any]]:
    """Substring search over topic names and Latin headers, best matches first."""
    needle = _normalize(query)
    if len(needle) < 2:
        return []

    scored: list[tuple[int, dict[str, Any]]] = []
    for module_id, topics in MODULES_CONTENT.items():
        for topic in topics:
            name = _normalize(topic.get("name", ""))
            lat = _normalize(topic.get("lat", ""))
            if needle in name:
                # earlier match = more likely the head term the student typed
                score = name.index(needle)
            elif needle in lat:
                score = 100 + lat.index(needle)
            else:
                continue
            scored.append((score, {"module_id": module_id, "num": topic["num"], "topic": topic}))

    scored.sort(key=lambda pair: pair[0])
    return [item for _, item in scored[:limit]]


def sample_tests(
    module_id: Optional[str] = None,
    topic_num: Optional[int] = None,
    limit: int = 10,
    rng: Optional[random.Random] = None,
) -> list[dict[str, Any]]:
    """Random test questions, each tagged with where it came from.

    Scope narrows from whole course -> one module -> one topic depending on what's passed.
    """
    rng = rng or random
    pool: list[dict[str, Any]] = []

    if module_id and topic_num is not None:
        topic = get_topic(module_id, topic_num)
        source = [(module_id, topic)] if topic else []
    elif module_id:
        source = [(module_id, topic) for topic in topics_of(module_id)]
    else:
        source = [(mid, topic) for mid, topics in MODULES_CONTENT.items() for topic in topics]

    for mid, topic in source:
        for question in topic.get("tests", []):
            if not question.get("options"):
                continue
            pool.append(
                {
                    "q": question.get("q", ""),
                    "options": question.get("options", []),
                    "correct": question.get("correct", 0),
                    "module_id": mid,
                    "topic_num": topic["num"],
                    "topic_name": topic.get("name", ""),
                }
            )

    if len(pool) <= limit:
        rng.shuffle(pool)
        return pool
    return rng.sample(pool, limit)


def sample_cards(
    module_id: str, topic_num: int, limit: int = 15, rng: Optional[random.Random] = None
) -> list[dict[str, Any]]:
    rng = rng or random
    topic = get_topic(module_id, topic_num)
    cards = list(topic.get("cards", [])) if topic else []
    rng.shuffle(cards)
    return cards[:limit]


def sample_pairs(
    module_id: Optional[str] = None,
    topic_num: Optional[int] = None,
    limit: int = 10,
    rng: Optional[random.Random] = None,
) -> list[dict[str, Any]]:
    rng = rng or random
    pool: list[dict[str, Any]] = []

    if module_id and topic_num is not None:
        topic = get_topic(module_id, topic_num)
        source = [topic] if topic else []
    elif module_id:
        source = topics_of(module_id)
    else:
        source = [topic for topics in MODULES_CONTENT.values() for topic in topics]

    for topic in source:
        for pair in topic.get("pairs", []):
            if pair.get("term") and pair.get("def"):
                pool.append({"term": pair["term"], "def": pair["def"]})

    if len(pool) <= limit:
        rng.shuffle(pool)
        return pool
    return rng.sample(pool, limit)


def all_pairs() -> list[dict[str, Any]]:
    return [
        {"term": pair["term"], "def": pair["def"], "topic": topic.get("name", "")}
        for topics in MODULES_CONTENT.values()
        for topic in topics
        for pair in topic.get("pairs", [])
        if pair.get("term") and pair.get("def")
    ]


def build_pair_question(
    pair: dict[str, Any], pool: list[dict[str, Any]], rng: Optional[random.Random] = None
) -> dict[str, Any]:
    """Turn a term/definition pair into a 4-option multiple choice question.

    Distractors are other pairs' definitions, deduplicated against the right answer so a question
    can never show the correct text twice.
    """
    rng = rng or random
    correct_def = pair["def"]
    candidates = [p["def"] for p in pool if p["def"] != correct_def]
    distractors = rng.sample(candidates, min(3, len(candidates))) if candidates else []
    options = distractors + [correct_def]
    rng.shuffle(options)
    return {
        "q": pair["term"],
        "options": options,
        "correct": options.index(correct_def),
    }
