"""Generic UI for validated subjects generated by the Telegram course pipeline."""
import html
from pathlib import Path

from aiogram import F, Router
from aiogram.types import CallbackQuery, FSInputFile, InlineKeyboardButton
from aiogram.utils.keyboard import InlineKeyboardBuilder

import telegram_bot as tb

router = Router()
LESSONS_PER_PAGE = 12
BIOCHEMISTRY_LESSONS_PER_PAGE = 8


def _lessons_per_page(course_index: int) -> int:
    course = tb.DYNAMIC_COURSES[course_index]
    if course.get("id") == "biochemistry":
        return BIOCHEMISTRY_LESSONS_PER_PAGE
    return LESSONS_PER_PAGE


def _biochemistry_button_title(title: str, group_title: str) -> str:
    """Make dense practicum headings distinguishable on narrow Telegram screens."""
    if title == group_title:
        return "Обзор занятия"

    standalone = {
        "Допуск": "Допуск к занятию",
        "Ходы определения": "Лабораторные определения",
        "Контроль к допуску": "Контроль допуска",
        "Вопросы для самоподготовки": "Самоподготовка",
    }
    if title in standalone:
        return standalone[title]

    if " · " not in title:
        return title

    category, detail = title.split(" · ", 1)
    if category == "Ходы определения":
        return f"Опыт · {detail}"
    if category == "Контроль к допуску":
        return f"Контроль · {detail.removeprefix('Вопрос ')}"
    if category == "Вопросы для самоподготовки":
        return f"Вопрос · {detail.removeprefix('Вопрос ')}"
    return f"{category} · {detail.removeprefix('Вопрос ')}"


def _group_button_title(course_index: int, group: dict, lesson: dict) -> str:
    if tb.DYNAMIC_COURSES[course_index].get("id") == "biochemistry":
        return _biochemistry_button_title(lesson["title"], group["title"])
    return lesson["title"]


def get_maintenance_keyboard(course: dict):
    builder = InlineKeyboardBuilder()
    course_number = course.get("course", 2)
    builder.button(text=f"🔙 К {course_number}-му курсу", callback_data=f"course_menu:{course_number}")
    return builder.as_markup()


async def deny_maintenance_course(callback: CallbackQuery, course_index: int) -> bool:
    course = get_dynamic_item(course_index)
    if not course or not tb.dynamic_course_under_maintenance(course):
        return False
    await callback.answer("Раздел временно закрыт на переработку", show_alert=True)
    await tb.safe_edit_text(
        callback.message,
        f"🛠 <b>{html.escape(course['title'])} — техобслуживание</b>\n{tb.DIVIDER}\n\n"
        "Раздел временно закрыт на полную переработку материалов и структуры. "
        "Мы вернём его после повторной проверки качества.",
        parse_mode="HTML",
        reply_markup=get_maintenance_keyboard(course),
    )
    return True


def get_dynamic_course_keyboard(course_index: int):
    builder = InlineKeyboardBuilder()
    for section_index, section in enumerate(tb.DYNAMIC_COURSES[course_index]["sections"]):
        builder.button(text=section["title"], callback_data=f"dyn_s:{course_index}:{section_index}")
    course = tb.DYNAMIC_COURSES[course_index]
    if course.get("ai_mode"):
        builder.button(text="🤖 VMedA AI по предмету", callback_data=f"dyn_ai:{course_index}")
    course_number = course.get("course", 2)
    builder.button(text=f"🔙 К {course_number}-му курсу", callback_data=f"course_menu:{course_number}")
    builder.adjust(1)
    return builder.as_markup()


@router.callback_query(F.data.startswith("dyn_ai:"))
async def cb_dynamic_ai(callback: CallbackQuery):
    try:
        course_index = int(callback.data.split(":")[1])
    except (ValueError, IndexError):
        await callback.answer("Предмет не найден", show_alert=True)
        return
    course = get_dynamic_item(course_index)
    if not course or not course.get("ai_mode"):
        await callback.answer("AI для предмета не найден", show_alert=True)
        return
    if await deny_maintenance_course(callback, course_index):
        return
    await tb.begin_ai_session(callback, mode=course["ai_mode"])


def get_dynamic_section_keyboard(course_index: int, section_index: int):
    builder = InlineKeyboardBuilder()
    section = tb.DYNAMIC_COURSES[course_index]["sections"][section_index]
    if section.get("groups"):
        for group_index, group in enumerate(section["groups"]):
            builder.button(text=group["title"], callback_data=f"dyn_g:{course_index}:{section_index}:{group_index}:0")
        builder.button(text="🔙 К разделам", callback_data=f"dyn_c:{course_index}")
        builder.adjust(1)
        return builder.as_markup()
    for lesson_index, lesson in enumerate(section["lessons"]):
        builder.button(text=lesson["title"], callback_data=f"dyn_l:{course_index}:{section_index}:{lesson_index}")
    builder.button(text="🔙 К разделам", callback_data=f"dyn_c:{course_index}")
    builder.adjust(1)
    return builder.as_markup()


def get_dynamic_group_keyboard(course_index: int, section_index: int, group_index: int, page: int):
    builder = InlineKeyboardBuilder()
    group = tb.DYNAMIC_COURSES[course_index]["sections"][section_index]["groups"][group_index]
    lessons = group["lessons"]
    page_size = _lessons_per_page(course_index)
    page_count = max(1, (len(lessons) + page_size - 1) // page_size)
    page = min(max(page, 0), page_count - 1)
    start = page * page_size
    for lesson_index in range(start, min(start + page_size, len(lessons))):
        builder.button(
            text=_group_button_title(course_index, group, lessons[lesson_index]),
            callback_data=f"dyn_gl:{course_index}:{section_index}:{group_index}:{lesson_index}",
        )
    # Long educational labels must occupy the full Telegram message width.
    builder.adjust(1)
    nav = []
    if page > 0:
        nav.append(InlineKeyboardButton(text="⬅️", callback_data=f"dyn_g:{course_index}:{section_index}:{group_index}:{page - 1}"))
    nav.append(InlineKeyboardButton(text=f"{page + 1}/{page_count}", callback_data="noop"))
    if page + 1 < page_count:
        nav.append(InlineKeyboardButton(text="➡️", callback_data=f"dyn_g:{course_index}:{section_index}:{group_index}:{page + 1}"))
    builder.row(*nav)
    builder.row(InlineKeyboardButton(text="🔙 К подразделам", callback_data=f"dyn_s:{course_index}:{section_index}"))
    return builder.as_markup()


def get_dynamic_group_lesson_keyboard(
    course_index: int,
    section_index: int,
    group_index: int,
    lesson_index: int,
    content_page: int = 0,
):
    lessons = tb.DYNAMIC_COURSES[course_index]["sections"][section_index]["groups"][group_index]["lessons"]
    builder = InlineKeyboardBuilder()
    pages = lessons[lesson_index].get("content_pages") or [lessons[lesson_index]["content"]]
    if len(pages) > 1:
        page_buttons = [
            InlineKeyboardButton(
                text=f"• {page_number + 1} •" if page_number == content_page else str(page_number + 1),
                callback_data=(
                    "noop" if page_number == content_page
                    else f"dyn_glp:{course_index}:{section_index}:{group_index}:{lesson_index}:{page_number}"
                ),
            )
            for page_number in range(len(pages))
        ]
        for start in range(0, len(page_buttons), 4):
            builder.row(*page_buttons[start:start + 4])
        page = lesson_index // _lessons_per_page(course_index)
        builder.row(InlineKeyboardButton(
            text="🔙 К темам",
            callback_data=f"dyn_g:{course_index}:{section_index}:{group_index}:{page}",
        ))
        return builder.as_markup()

    nav = []
    if lesson_index > 0:
        nav.append(InlineKeyboardButton(text="⬅️", callback_data=f"dyn_gl:{course_index}:{section_index}:{group_index}:{lesson_index - 1}"))
    if lesson_index + 1 < len(lessons):
        nav.append(InlineKeyboardButton(text="➡️", callback_data=f"dyn_gl:{course_index}:{section_index}:{group_index}:{lesson_index + 1}"))
    if nav:
        builder.row(*nav)
    page = lesson_index // _lessons_per_page(course_index)
    builder.row(InlineKeyboardButton(text="🔙 К темам", callback_data=f"dyn_g:{course_index}:{section_index}:{group_index}:{page}"))
    return builder.as_markup()


def _group_lesson_message(lesson: dict, content_page: int = 0) -> str:
    pages = lesson.get("content_pages") or [lesson["content"]]
    page_suffix = f" · страница {content_page + 1}/{len(pages)}" if len(pages) > 1 else ""
    return (
        f"📖 <b>{html.escape(lesson['title'])}{page_suffix}</b>\n"
        f"{tb.DIVIDER}\n\n{pages[content_page]}"
    )


def get_dynamic_lesson_keyboard(course_index: int, section_index: int, lesson_index: int):
    builder = InlineKeyboardBuilder()
    lessons = tb.DYNAMIC_COURSES[course_index]["sections"][section_index]["lessons"]
    navigation = []
    if lesson_index > 0:
        navigation.append(InlineKeyboardButton(
            text="⬅️", callback_data=f"dyn_l:{course_index}:{section_index}:{lesson_index - 1}",
        ))
    if lesson_index + 1 < len(lessons):
        navigation.append(InlineKeyboardButton(
            text="➡️", callback_data=f"dyn_l:{course_index}:{section_index}:{lesson_index + 1}",
        ))
    if navigation:
        builder.row(*navigation)
    builder.row(InlineKeyboardButton(text="🔙 К темам", callback_data=f"dyn_s:{course_index}:{section_index}"))
    return builder.as_markup()


def get_dynamic_item(course_index: int, section_index: int | None = None, lesson_index: int | None = None):
    if course_index < 0 or (section_index is not None and section_index < 0) or (lesson_index is not None and lesson_index < 0):
        return None
    try:
        course = tb.DYNAMIC_COURSES[course_index]
        if section_index is None:
            return course
        section = course["sections"][section_index]
        return section if lesson_index is None else section["lessons"][lesson_index]
    except (IndexError, KeyError, TypeError):
        return None


@router.callback_query(F.data.startswith("dyn_c:"))
async def cb_dynamic_course(callback: CallbackQuery):
    try:
        course_index = int(callback.data.split(":")[1])
    except (ValueError, IndexError):
        await callback.answer("Предмет не найден", show_alert=True)
        return
    course = get_dynamic_item(course_index)
    if not course:
        await callback.answer("Предмет не найден", show_alert=True)
        return
    if await deny_maintenance_course(callback, course_index):
        return
    await callback.answer()
    await tb.safe_edit_text(
        callback.message,
        f"{course.get('emoji', '📚')} <b>{html.escape(course['title'])}</b>\n{tb.DIVIDER}\n\n"
        f"{html.escape(course.get('description', 'Выберите раздел:'))}",
        parse_mode="HTML",
        reply_markup=get_dynamic_course_keyboard(course_index),
    )


@router.callback_query(F.data.startswith("dyn_s:"))
async def cb_dynamic_section(callback: CallbackQuery):
    try:
        _, course_raw, section_raw = callback.data.split(":")
        course_index, section_index = int(course_raw), int(section_raw)
    except (ValueError, IndexError):
        await callback.answer("Раздел не найден", show_alert=True)
        return
    section = get_dynamic_item(course_index, section_index)
    if not section:
        await callback.answer("Раздел не найден", show_alert=True)
        return
    if await deny_maintenance_course(callback, course_index):
        return
    await callback.answer()
    await tb.safe_edit_text(
        callback.message,
        f"📂 <b>{html.escape(section['title'])}</b>\n{tb.DIVIDER}\n\nВыберите тему:",
        parse_mode="HTML",
        reply_markup=get_dynamic_section_keyboard(course_index, section_index),
    )


@router.callback_query(F.data.startswith("dyn_g:"))
async def cb_dynamic_group(callback: CallbackQuery):
    try:
        _, c, s, g, p = callback.data.split(":")
        course_index, section_index, group_index, page = map(int, (c, s, g, p))
        group = tb.DYNAMIC_COURSES[course_index]["sections"][section_index]["groups"][group_index]
    except (ValueError, IndexError, KeyError, TypeError):
        await callback.answer("Подраздел не найден", show_alert=True)
        return
    if await deny_maintenance_course(callback, course_index):
        return
    page_size = _lessons_per_page(course_index)
    page_count = max(1, (len(group["lessons"]) + page_size - 1) // page_size)
    if page < 0 or page >= page_count:
        await callback.answer("Страница не найдена", show_alert=True)
        return
    await callback.answer()
    start = page * page_size + 1
    end = min((page + 1) * page_size, len(group["lessons"]))
    page_hint = f"Темы {start}–{end} из {len(group['lessons'])}"
    await tb.safe_edit_text(
        callback.message,
        f"📚 <b>{html.escape(group['title'])}</b>\n{tb.DIVIDER}\n\n"
        f"{page_hint}. Выберите нужную тему:",
        parse_mode="HTML",
        reply_markup=get_dynamic_group_keyboard(course_index, section_index, group_index, page),
    )


@router.callback_query(F.data.startswith("dyn_gl:"))
async def cb_dynamic_group_lesson(callback: CallbackQuery):
    try:
        _, c, s, g, l = callback.data.split(":")
        course_index, section_index, group_index, lesson_index = map(int, (c, s, g, l))
        course = tb.DYNAMIC_COURSES[course_index]
        lesson = course["sections"][section_index]["groups"][group_index]["lessons"][lesson_index]
    except (ValueError, IndexError, KeyError, TypeError):
        await callback.answer("Тема не найдена", show_alert=True)
        return
    if await deny_maintenance_course(callback, course_index):
        return
    await callback.answer()
    await tb.safe_edit_text(
        callback.message,
        _group_lesson_message(lesson),
        parse_mode="HTML",
        reply_markup=get_dynamic_group_lesson_keyboard(
            course_index, section_index, group_index, lesson_index,
        ),
    )
    for media in lesson.get("media", []):
        media_path = Path(media["path"])
        if not media_path.is_absolute():
            media_path = Path(__file__).resolve().parents[1] / media_path
        if media_path.is_file():
            await callback.message.answer_photo(FSInputFile(media_path), caption=html.escape(media.get("caption", "")), parse_mode="HTML")


@router.callback_query(F.data.startswith("dyn_glp:"))
async def cb_dynamic_group_lesson_page(callback: CallbackQuery):
    try:
        _, c, s, g, l, p = callback.data.split(":")
        course_index, section_index, group_index, lesson_index, content_page = map(int, (c, s, g, l, p))
        lesson = tb.DYNAMIC_COURSES[course_index]["sections"][section_index]["groups"][group_index]["lessons"][lesson_index]
        pages = lesson.get("content_pages") or [lesson["content"]]
        if content_page < 0 or content_page >= len(pages):
            raise IndexError
    except (ValueError, IndexError, KeyError, TypeError):
        await callback.answer("Страница не найдена", show_alert=True)
        return
    if await deny_maintenance_course(callback, course_index):
        return
    await callback.answer()
    await tb.safe_edit_text(
        callback.message,
        _group_lesson_message(lesson, content_page),
        parse_mode="HTML",
        reply_markup=get_dynamic_group_lesson_keyboard(
            course_index, section_index, group_index, lesson_index, content_page,
        ),
    )


@router.callback_query(F.data.startswith("dyn_l:"))
async def cb_dynamic_lesson(callback: CallbackQuery):
    try:
        _, course_raw, section_raw, lesson_raw = callback.data.split(":")
        course_index, section_index, lesson_index = int(course_raw), int(section_raw), int(lesson_raw)
    except (ValueError, IndexError):
        await callback.answer("Тема не найдена", show_alert=True)
        return
    lesson = get_dynamic_item(course_index, section_index, lesson_index)
    if not lesson:
        await callback.answer("Тема не найдена", show_alert=True)
        return
    if await deny_maintenance_course(callback, course_index):
        return
    await callback.answer()
    course = get_dynamic_item(course_index)
    sources = lesson.get("sources", []) if course.get("show_sources", True) else []
    source_text = ""
    if sources:
        source_text = "\n\n📎 <b>Источники:</b> " + ", ".join(html.escape(item) for item in sources)
    await tb.safe_edit_text(
        callback.message,
        f"📖 <b>{html.escape(lesson['title'])}</b>\n{tb.DIVIDER}\n\n{lesson['content']}{source_text}",
        parse_mode="HTML",
        reply_markup=get_dynamic_lesson_keyboard(course_index, section_index, lesson_index),
    )
    for media in lesson.get("media", []):
        media_path = Path(media["path"])
        if not media_path.is_absolute():
            media_path = Path(__file__).resolve().parents[1] / media_path
        if media_path.is_file():
            await callback.message.answer_photo(
                FSInputFile(media_path),
                caption=html.escape(media.get("caption", "")),
                parse_mode="HTML",
            )
